platform :ios, '9.0'
inhibit_all_warnings!

target 'CineKobe' do
  pod 'Moya', '~> 11.0'
end

target 'CineKobeTests' do
    inherit! :complete
    pod 'Nimble', '~> 7.0.1'
    pod 'Quick', '~> 1.0.0'
end
